package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.MavenBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildDeploy'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildDeploy")) {
    expectSteps {
        maven {
            name = "Make Some Test"

            conditions {
                doesNotContain("teamcity.build.branch", "master")
            }
            goals = "clean test"
            runnerArgs = "-Dmaven.test.failure.ignore=true"
            userSettingsSelection = "custom"
        }
        maven {
            name = "Deploy to Nexus"

            conditions {
                contains("teamcity.build.branch", "marster")
            }
            goals = "clean deploy"
            runnerArgs = "-Dmaven.test.failure.ignore=true"
            userSettingsSelection = "custom"
        }
    }
    steps {
        update<MavenBuildStep>(0) {
            clearConditions()

            conditions {
                doesNotContain("teamcity.build.branch", "master")
            }
            goals = "mvn clean test"
        }
        update<MavenBuildStep>(1) {
            clearConditions()

            conditions {
                contains("teamcity.build.branch", "marster")
            }
            goals = "mvn clean package deploy"
        }
    }
}
